[package]
name = "simple-redis"
version = "0.1.0"
authors = ["David Chen"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
