[package]
name = "simple-redis"
version = "0.1.0"
authors = ["David Chen"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.0"
enum_dispatch = "0.3.13"
thiserror = "1.0.61"
